openapi: 3.0.3
info:
  title: Bugsy API (V1)
  description: Multi-level security project API documentation (V1 - vulnerable level)
  version: 1.0.0
servers:
  - url: http://localhost/Bugsy/api/v1
paths:

  /register:
    post:
      summary: Register a new user
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /login:
    post:
      summary: Login and get auth token
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /logout:
    post:
      summary: Logout the current user
      tags: [Authentication]
      responses:
        '200':
          description: Logout successful

  /products:
    get:
      summary: List all products
      tags: [Products]
      responses:
        '200':
          description: OK
    post:
      summary: Create a product (admin)
      tags: [Products]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                category_id:
                  type: integer
                brand_id:
                  type: integer
      responses:
        '201':
          description: Product created

  /products/{id}:
    get:
      summary: Get a product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
    post:
      summary: Update a product (admin)
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                category_id:
                  type: integer
                brand_id:
                  type: integer
      responses:
        '200':
          description: Product updated
    delete:
      summary: Delete a product (admin)
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product deleted

  /products/{id}/images:
    get:
      summary: Get product images
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of images
    post:
      summary: Upload additional images
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: string
                  format: binary
      responses:
        '201':
          description: Images uploaded

  /products/images/{id}:
    delete:
      summary: Delete a product image
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Image deleted

  /products/{id}/images/replace:
    post:
      summary: Replace product images
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Images replaced

# NOTE: You can continue adding /cart, /orders, /reviews, /categories, /brands, /user, /search, /test endpoints similarly

tags:
  - name: Authentication
  - name: Products
  - name: Cart
  - name: Orders
  - name: Reviews
  - name: Categories
  - name: Brands
  - name: User
  - name: Search
  - name: Test
