/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forgetPassword'
import { Route as MainShopRouteImport } from './routes/_main/shop'
import { Route as MainFavouritsRouteImport } from './routes/_main/favourits'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as MainCheckoutRouteImport } from './routes/_main/checkout'
import { Route as MainCartRouteImport } from './routes/_main/cart'
import { Route as MainCardInfoRouteImport } from './routes/_main/cardInfo'
import { Route as MainAccountRouteImport } from './routes/_main/account'
import { Route as MainAboutRouteImport } from './routes/_main/about'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainShopRoute = MainShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFavouritsRoute = MainFavouritsRouteImport.update({
  id: '/favourits',
  path: '/favourits',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCheckoutRoute = MainCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCartRoute = MainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCardInfoRoute = MainCardInfoRouteImport.update({
  id: '/cardInfo',
  path: '/cardInfo',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAccountRoute = MainAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/account': typeof MainAccountRoute
  '/cardInfo': typeof MainCardInfoRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/contact': typeof MainContactRoute
  '/favourits': typeof MainFavouritsRoute
  '/shop': typeof MainShopRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/account': typeof MainAccountRoute
  '/cardInfo': typeof MainCardInfoRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/contact': typeof MainContactRoute
  '/favourits': typeof MainFavouritsRoute
  '/shop': typeof MainShopRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/account': typeof MainAccountRoute
  '/_main/cardInfo': typeof MainCardInfoRoute
  '/_main/cart': typeof MainCartRoute
  '/_main/checkout': typeof MainCheckoutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/favourits': typeof MainFavouritsRoute
  '/_main/shop': typeof MainShopRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/about'
    | '/account'
    | '/cardInfo'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/favourits'
    | '/shop'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/account'
    | '/cardInfo'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/favourits'
    | '/shop'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/_main/about'
    | '/_main/account'
    | '/_main/cardInfo'
    | '/_main/cart'
    | '/_main/checkout'
    | '/_main/contact'
    | '/_main/favourits'
    | '/_main/shop'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgetPassword': {
      id: '/auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/auth/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/shop': {
      id: '/_main/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MainShopRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/favourits': {
      id: '/_main/favourits'
      path: '/favourits'
      fullPath: '/favourits'
      preLoaderRoute: typeof MainFavouritsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/checkout': {
      id: '/_main/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof MainCheckoutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cart': {
      id: '/_main/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainCartRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cardInfo': {
      id: '/_main/cardInfo'
      path: '/cardInfo'
      fullPath: '/cardInfo'
      preLoaderRoute: typeof MainCardInfoRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/account': {
      id: '/_main/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MainAccountRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainAccountRoute: typeof MainAccountRoute
  MainCardInfoRoute: typeof MainCardInfoRoute
  MainCartRoute: typeof MainCartRoute
  MainCheckoutRoute: typeof MainCheckoutRoute
  MainContactRoute: typeof MainContactRoute
  MainFavouritsRoute: typeof MainFavouritsRoute
  MainShopRoute: typeof MainShopRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainAccountRoute: MainAccountRoute,
  MainCardInfoRoute: MainCardInfoRoute,
  MainCartRoute: MainCartRoute,
  MainCheckoutRoute: MainCheckoutRoute,
  MainContactRoute: MainContactRoute,
  MainFavouritsRoute: MainFavouritsRoute,
  MainShopRoute: MainShopRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
