/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forgetPassword'
import { Route as MainShopRouteImport } from './routes/_main/shop'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as MainCheckoutRouteImport } from './routes/_main/checkout'
import { Route as MainCartRouteImport } from './routes/_main/cart'
import { Route as MainCardInfoRouteImport } from './routes/_main/cardInfo'
import { Route as MainAdminRouteImport } from './routes/_main/admin'
import { Route as MainAccountRouteImport } from './routes/_main/account'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainDashboardRouteRouteImport } from './routes/_main/dashboard/route'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as MainDashboardUsersRouteImport } from './routes/_main/dashboard/users'
import { Route as MainDashboardProductRouteImport } from './routes/_main/dashboard/product'
import { Route as MainDashboardOrdersRouteImport } from './routes/_main/dashboard/orders'
import { Route as MainDashboardCategoriesRouteImport } from './routes/_main/dashboard/categories'
import { Route as MainDashboardBrandsRouteImport } from './routes/_main/dashboard/brands'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainShopRoute = MainShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCheckoutRoute = MainCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCartRoute = MainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCardInfoRoute = MainCardInfoRouteImport.update({
  id: '/cardInfo',
  path: '/cardInfo',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminRoute = MainAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAccountRoute = MainAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardRouteRoute = MainDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardUsersRoute = MainDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardProductRoute = MainDashboardProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardOrdersRoute = MainDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardCategoriesRoute = MainDashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)
const MainDashboardBrandsRoute = MainDashboardBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => MainDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof MainDashboardRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/account': typeof MainAccountRoute
  '/admin': typeof MainAdminRoute
  '/cardInfo': typeof MainCardInfoRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/contact': typeof MainContactRoute
  '/shop': typeof MainShopRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof MainIndexRoute
  '/dashboard/brands': typeof MainDashboardBrandsRoute
  '/dashboard/categories': typeof MainDashboardCategoriesRoute
  '/dashboard/orders': typeof MainDashboardOrdersRoute
  '/dashboard/product': typeof MainDashboardProductRoute
  '/dashboard/users': typeof MainDashboardUsersRoute
  '/dashboard/': typeof MainDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/account': typeof MainAccountRoute
  '/admin': typeof MainAdminRoute
  '/cardInfo': typeof MainCardInfoRoute
  '/cart': typeof MainCartRoute
  '/checkout': typeof MainCheckoutRoute
  '/contact': typeof MainContactRoute
  '/shop': typeof MainShopRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof MainIndexRoute
  '/dashboard/brands': typeof MainDashboardBrandsRoute
  '/dashboard/categories': typeof MainDashboardCategoriesRoute
  '/dashboard/orders': typeof MainDashboardOrdersRoute
  '/dashboard/product': typeof MainDashboardProductRoute
  '/dashboard/users': typeof MainDashboardUsersRoute
  '/dashboard': typeof MainDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_main/dashboard': typeof MainDashboardRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/account': typeof MainAccountRoute
  '/_main/admin': typeof MainAdminRoute
  '/_main/cardInfo': typeof MainCardInfoRoute
  '/_main/cart': typeof MainCartRoute
  '/_main/checkout': typeof MainCheckoutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/shop': typeof MainShopRoute
  '/auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_main/': typeof MainIndexRoute
  '/_main/dashboard/brands': typeof MainDashboardBrandsRoute
  '/_main/dashboard/categories': typeof MainDashboardCategoriesRoute
  '/_main/dashboard/orders': typeof MainDashboardOrdersRoute
  '/_main/dashboard/product': typeof MainDashboardProductRoute
  '/_main/dashboard/users': typeof MainDashboardUsersRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/account'
    | '/admin'
    | '/cardInfo'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/product'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/account'
    | '/admin'
    | '/cardInfo'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/orders'
    | '/dashboard/product'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/_main/dashboard'
    | '/_main/about'
    | '/_main/account'
    | '/_main/admin'
    | '/_main/cardInfo'
    | '/_main/cart'
    | '/_main/checkout'
    | '/_main/contact'
    | '/_main/shop'
    | '/auth/forgetPassword'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/_main/'
    | '/_main/dashboard/brands'
    | '/_main/dashboard/categories'
    | '/_main/dashboard/orders'
    | '/_main/dashboard/product'
    | '/_main/dashboard/users'
    | '/_main/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgetPassword': {
      id: '/auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/auth/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/shop': {
      id: '/_main/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MainShopRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/checkout': {
      id: '/_main/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof MainCheckoutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cart': {
      id: '/_main/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainCartRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cardInfo': {
      id: '/_main/cardInfo'
      path: '/cardInfo'
      fullPath: '/cardInfo'
      preLoaderRoute: typeof MainCardInfoRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin': {
      id: '/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainAdminRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/account': {
      id: '/_main/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MainAccountRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/users': {
      id: '/_main/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof MainDashboardUsersRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/product': {
      id: '/_main/dashboard/product'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof MainDashboardProductRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/orders': {
      id: '/_main/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof MainDashboardOrdersRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/categories': {
      id: '/_main/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof MainDashboardCategoriesRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
    '/_main/dashboard/brands': {
      id: '/_main/dashboard/brands'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof MainDashboardBrandsRouteImport
      parentRoute: typeof MainDashboardRouteRoute
    }
  }
}

interface MainDashboardRouteRouteChildren {
  MainDashboardBrandsRoute: typeof MainDashboardBrandsRoute
  MainDashboardCategoriesRoute: typeof MainDashboardCategoriesRoute
  MainDashboardOrdersRoute: typeof MainDashboardOrdersRoute
  MainDashboardProductRoute: typeof MainDashboardProductRoute
  MainDashboardUsersRoute: typeof MainDashboardUsersRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
}

const MainDashboardRouteRouteChildren: MainDashboardRouteRouteChildren = {
  MainDashboardBrandsRoute: MainDashboardBrandsRoute,
  MainDashboardCategoriesRoute: MainDashboardCategoriesRoute,
  MainDashboardOrdersRoute: MainDashboardOrdersRoute,
  MainDashboardProductRoute: MainDashboardProductRoute,
  MainDashboardUsersRoute: MainDashboardUsersRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
}

const MainDashboardRouteRouteWithChildren =
  MainDashboardRouteRoute._addFileChildren(MainDashboardRouteRouteChildren)

interface MainRouteRouteChildren {
  MainDashboardRouteRoute: typeof MainDashboardRouteRouteWithChildren
  MainAboutRoute: typeof MainAboutRoute
  MainAccountRoute: typeof MainAccountRoute
  MainAdminRoute: typeof MainAdminRoute
  MainCardInfoRoute: typeof MainCardInfoRoute
  MainCartRoute: typeof MainCartRoute
  MainCheckoutRoute: typeof MainCheckoutRoute
  MainContactRoute: typeof MainContactRoute
  MainShopRoute: typeof MainShopRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainDashboardRouteRoute: MainDashboardRouteRouteWithChildren,
  MainAboutRoute: MainAboutRoute,
  MainAccountRoute: MainAccountRoute,
  MainAdminRoute: MainAdminRoute,
  MainCardInfoRoute: MainCardInfoRoute,
  MainCartRoute: MainCartRoute,
  MainCheckoutRoute: MainCheckoutRoute,
  MainContactRoute: MainContactRoute,
  MainShopRoute: MainShopRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
